version: '2'
services:
  examenpracticocinco-app:
    image: examenpracticocinco
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://examenpracticocinco-postgresql:5432/examenpracticocinco
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  examenpracticocinco-postgresql:
    extends:
      file: postgresql.yml
      service: examenpracticocinco-postgresql
